version: '3.8'

services:
  web:
    build: .
    command: /start.sh
    volumes:
      - .:/app
    ports:
      - "5000:80"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./weather.conf:/etc/nginx/conf.d/default.conf
